[package]
name = "hello"
version = "0.1.0"
edition = "2021"
description = "hello world"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
